### PR TITLE
chore: add README

### PR DESCRIPTION
**Pull request by nlf**

### CODE REVIEW

**Comment by nlf** [comment]
boop

**Comment by nlf** [comment]
boop

**Comment by nlf** [comment]
asdf

**Comment by nlf** [comment]
asdf

**Comment by lukekarrys** [comment]
📣 commenting! 📣

**Comment by nlf** [comment]
asdf

**Comment by nlf** [comment]
@npm-cli-bot rebase merge

**Comment by nlf** [comment]
@npm-cli-bot rebase merge

**Comment by nlf** [comment]
@npm-cli-bot rebase merge

**Comment by nlf** [comment]
@npm-cli-bot rebase merge

**Comment by nlf** [comment]
@npm-cli-bot rebase merge

**Comment by nlf** [comment]
@npm-cli-bot rebase merge

**Pull request closed without merging**
